//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Integrador_3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PI3Entities : DbContext
    {
        public PI3Entities()
            : base("name=PI3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Usuario> Usuarios { get; set; }
        public DbSet<Unidad> Unidads { get; set; }
        public DbSet<Servicio> Servicios { get; set; }
        public DbSet<Tarjeta> Tarjetas { get; set; }
    }
}
