//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Integrador_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicio
    {
        public int Id { get; set; }
        public short TipoUsuario { get; set; }
        public System.Guid Unidad { get; set; }
        public System.Guid Usuario { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Unidad Unidad1 { get; set; }
        public virtual Usuario Usuarios { get; set; }
    }
}
