//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Integrador_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarjeta
    {
        public long Uid { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
