//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Integrador_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unidad
    {
        public Unidad()
        {
            this.Servicios = new HashSet<Servicio>();
        }
    
        public System.Guid Uid { get; set; }
        public string NoUnidad { get; set; }
    
        public virtual ICollection<Servicio> Servicios { get; set; }
    }
}
