//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Integrador_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.TipoUsuario = 1;
            this.Saldo = 0;
            this.Servicio = new HashSet<Servicio>();
        }
    
        public System.Guid Uid { get; set; }
        public string Nombre { get; set; }
        public string Domicilio { get; set; }
        public string Telefono { get; set; }
        public string TipoSangre { get; set; }
        public string Alergias { get; set; }
        public string Contacto { get; set; }
        public string TelefonoContacto { get; set; }
        public short TipoUsuario { get; set; }
        public int Saldo { get; set; }
        public long TarjetaAsignada { get; set; }
        public bool Sexo { get; set; }
    
        public virtual ICollection<Servicio> Servicio { get; set; }
        public virtual Tarjeta Tarjetas { get; set; }
    }
}
